# Generated by Django 4.2.26 on 2026-02-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrantes', to='api.sucursales')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_salientes', to='api.sucursales')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de Almacén'), ('VENTA', 'Salida por Venta'), ('TRASPASO_SALIDA', 'Envío a otra Sucursal'), ('TRASPASO_ENTRADA', 'Recepción de otra Sucursal'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('saldo_historico', models.IntegerField(editable=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='ID de Venta o Traspaso', max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursales')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
