# Generated by Django 4.2.26 on 2026-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solicitudtraspaso_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='afecta_inventario',
            field=models.BooleanField(default=False),
        ),
    ]
