# Generated by Django 4.2.26 on 2026-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesWeb',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Contacto'), ('ATENDIDA', 'Atendida / Cotizada'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes Web',
            },
        ),
    ]
