# Generated by Django 4.2.26 on 2026-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_solicitudesweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesweb',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_web', to='api.cotizaciones'),
        ),
    ]
